---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: Install Pacemaker
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - pcs
    - pacemaker
    - policycoreutils-python
    - psmisc

# - name: Set password for local hacluster user
#   command: "echo clusterpassword123 | passwd --stdin hacluster"
- name: upgrade pexpect
  become: true
  command: "sudo pip install pexpect --upgrade"
  ignore_errors: true
- name: step7
  become: true
  expect:
    command: "passwd hacluster"
    responses:
      Новый пароль : 'clusterpassword123'
- name: Enable Pacemaker service
  systemd:
    name: pcsd.service
    enabled: true
    state: started

- name: Configuring firewall services
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - high-availability

- meta: flush_handlers
...
