---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: Set timezone
  command: "{{ item }}"
  with_items: 
    - "timedatectl set-timezone Europe/Moscow"
    - "timedatectl set-ntp true"

- name: Set locale
  command: "localectl set-locale LC_CTYPE=en_US.utf8"
  
- name: Install additional packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - firewalld
    - python2-cryptography
    - setools-console
    - libsemanage-python
    - policycoreutils-python

- name: Set hostname
  command: "sudo hostnamectl set-hostname {{ name }}"

- name: copy /etc/hosts
  copy:
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      {{ ip_pcs1 }} pcs1.domain.test pcs1
      {{ ip_pcs2 }} pcs2.domain.test pcs2
      {{ ip_pcs3 }} pcs3.domain.test pcs3
    dest: "/etc/hosts"  
    mode: 644
    owner: root
    group: root

- name: Enable and start FirewallD
  systemd:
    name: firewalld
    state: started
    enabled: true
...
