---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: Install components for building
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - iscsi-initiator-utils

- name: write_wwn_pcs1
  copy:
    content: "{{ wwn_client }}"
    dest: "/etc/iscsi/initiatorname.iscsi"
    owner: root
    group: root
    mode: "0644"

- name: Enable iscsi service
  systemd:
    name: iscsi
    enabled: true
    state: started

- name: discover iscsi_server
  become: true
  command: "iscsiadm -m discovery -t st -p 192.168.56.204"

- name: login iscsi
  become: true
  command: "iscsiadm -m node -l -T {{iqn_server}}"
...
